# Data Exploration:

In [144]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn. linear_model import LinearRegression

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import cross_val_score

In [145]:
cars_df = pd.read_csv('CAR DETAILS FROM CAR DEKHO.csv')

In [146]:
cars_df.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [147]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB


In [148]:
cars_df.shape

(4340, 8)

In [149]:
cars_df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [150]:
cars_df.duplicated().sum()

763

In [151]:
cars_df.drop_duplicates(inplace=True)

In [152]:
cars_df.shape

(3577, 8)

# Feature Engineering:

In [153]:
for col in cars_df.columns:
    print('Unique values of ' + col)
    print(cars_df[col].unique())
    print("=======================")

Unique values of name
['Maruti 800 AC' 'Maruti Wagon R LXI Minor' 'Hyundai Verna 1.6 SX' ...
 'Mahindra Verito 1.5 D6 BSIII'
 'Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV'
 'Hyundai i20 Magna 1.4 CRDi']
Unique values of year
[2007 2012 2017 2014 2016 2015 2018 2019 2013 2011 2010 2009 2006 1996
 2005 2008 2004 1998 2003 2002 2020 2000 1999 2001 1995 1997 1992]
Unique values of selling_price
[  60000  135000  600000  250000  450000  140000  550000  240000  850000
  365000  260000 1650000  585000 1195000  390000 1964999 1425000  975000
 1190000  930000  525000 1735000 1375000  900000 1300000 1400000  229999
 1550000 1250000  625000 1050000  560000  290000  275000  411000  150000
  500000  100000  725000  401000  750000  310000  665000  465000  160000
  675000  300000   70000  151000  280000  350000  570000  125000  130000
  925000  200000  248000   80000  650000  495000  371000 1025000 8150000
  325000 1470000 2800000  210000 1150000 4500000 2750000 1975000  175000
 2500000  628000  399

In [154]:
def get_brand_name(car_name):
    car_name = car_name.split(' ')[0]
    return car_name.strip(' ')

In [155]:
cars_df['name'] = cars_df['name' ].apply(get_brand_name)

In [156]:
cars_df['name'].unique()

array(['Maruti', 'Hyundai', 'Datsun', 'Honda', 'Tata', 'Chevrolet',
       'Toyota', 'Jaguar', 'Mercedes-Benz', 'Audi', 'Skoda', 'Jeep',
       'BMW', 'Mahindra', 'Ford', 'Nissan', 'Renault', 'Fiat',
       'Volkswagen', 'Volvo', 'Mitsubishi', 'Land', 'Daewoo', 'MG',
       'Force', 'Isuzu', 'OpelCorsa', 'Ambassador', 'Kia'], dtype=object)

In [157]:
cars_df['name'].replace(['Maruti', 'Hyundai', 'Datsun', 'Honda', 'Tata', 'Chevrolet',
       'Toyota', 'Jaguar', 'Mercedes-Benz', 'Audi', 'Skoda', 'Jeep',
       'BMW', 'Mahindra', 'Ford', 'Nissan', 'Renault', 'Fiat',
       'Volkswagen', 'Volvo', 'Mitsubishi', 'Land', 'Daewoo', 'MG',
       'Force', 'Isuzu', 'OpelCorsa', 'Ambassador', 'Kia'],
                       [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]
                       ,inplace=True)

In [158]:
cars_df['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [159]:
cars_df['transmission'].replace(['Manual', 'Automatic'],[1,2],inplace=True)

In [160]:
cars_df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [161]:
cars_df['seller_type'].replace(['Individual', 'Dealer', 'Trustmark Dealer'],[1,2,3],inplace=True)

In [162]:
cars_df['fuel'].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [163]:
cars_df['fuel'].replace(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'],[1,2,3,4,5],inplace=True)

In [164]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3577 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           3577 non-null   int64 
 1   year           3577 non-null   int64 
 2   selling_price  3577 non-null   int64 
 3   km_driven      3577 non-null   int64 
 4   fuel           3577 non-null   int64 
 5   seller_type    3577 non-null   int64 
 6   transmission   3577 non-null   int64 
 7   owner          3577 non-null   object
dtypes: int64(7), object(1)
memory usage: 251.5+ KB


In [165]:
cars_df['owner'].unique()

array(['First Owner', 'Second Owner', 'Fourth & Above Owner',
       'Third Owner', 'Test Drive Car'], dtype=object)

In [166]:
cars_df['owner'].replace(['First Owner', 'Second Owner', 'Fourth & Above Owner',
       'Third Owner', 'Test Drive Car'],[1,2,3,4,5],inplace=True)

In [167]:
cars_df.head()

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0     1  2007          60000      70000     1            1             1   
1     1  2007         135000      50000     1            1             1   
2     2  2012         600000     100000     2            1             1   
3     3  2017         250000      46000     1            1             1   
4     4  2014         450000     141000     2            1             1   

   owner  
0      1  
1      1  
2      1  
3      1  
4      2

# Model Selection and Training:

In [168]:
input_data = cars_df.drop(columns=['selling_price'])
output_data =cars_df['selling_price']

In [169]:
X_train, X_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2)

In [170]:
model = LinearRegression()

In [171]:
model.fit(X_train, y_train)

LinearRegression()

In [172]:
predict = model.predict(X_test)

In [173]:
predict

array([ 1.24328946e+06,  6.12706425e+05,  4.74521114e+05,  1.26552110e+05,
        1.40378755e+06,  2.42110691e+05,  3.12853060e+05,  4.41405047e+05,
        3.71166799e+05,  3.47788330e+05,  6.40636007e+05,  4.70706899e+05,
        5.81096362e+05,  1.31373211e+06,  7.13048450e+05,  4.64675784e+05,
        6.71645159e+05,  2.20369659e+05,  5.97144868e+05,  4.25972171e+04,
        2.38307867e+05,  2.86305062e+05, -1.72841979e+05,  4.86869660e+05,
        5.79145824e+05,  6.81312959e+05,  2.88248175e+05,  4.95344700e+05,
        4.06601182e+05,  6.31304188e+05, -2.43997757e+05,  2.87842822e+05,
        4.15597474e+05,  3.46126311e+05,  7.26337968e+05,  5.82608611e+05,
        3.15716858e+05,  4.40348703e+05,  2.54492088e+05,  5.25537016e+05,
        6.34572430e+05,  8.48323015e+05,  1.64555356e+05,  6.76521052e+05,
        4.20408695e+05,  4.29725973e+05,  7.54904961e+05,  5.51862527e+05,
        1.21363717e+05,  5.35246046e+05,  4.66771016e+03,  2.63179816e+05,
        5.01744258e+05,  

In [175]:
#Random Forest
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)

In [176]:
#Gradient Boosting
gb_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
gb_model.fit(X_train, y_train)
gb_predictions = gb_model.predict(X_test)

# Model Evaluation:

In [177]:
X_train.head(1)

name  year  km_driven  fuel  seller_type  transmission  owner
654     1  2018      17500     1            1             1      1

In [178]:
input_df = pd.DataFrame(
[[1,2014,4000,1,1,1,1]],
columns=['name','year','km_driven','fuel', 'seller_type', 'transmission','owner'])

In [179]:
input_df

name  year  km_driven  fuel  seller_type  transmission  owner
0     1  2014       4000     1            1             1      1

In [180]:
model.predict(input_df)

array([355357.20575492])

In [181]:
rf_model.predict(input_df)

array([487983.33333333])

In [182]:
gb_model.predict(input_df)

array([320399.49449843])

In [183]:
# For Random Forest
rf_scores = cross_val_score(rf_model, input_data, output_data, cv=5, scoring='neg_mean_absolute_error')

# For Gradient Boosting
gb_scores = cross_val_score(gb_model, input_data, output_data, cv=5, scoring='neg_mean_absolute_error')

In [184]:
# Calculate MAE
mae = mean_absolute_error(y_test, predict)

# Calculate RMSE
rmse = np.sqrt(mean_squared_error(y_test, predict))

print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

MAE: 193730.74
RMSE: 308004.03


In [185]:
print("Random Forest MAE scores for each fold:", -rf_scores)
print("Gradient Boosting MAE scores for each fold:", -gb_scores)

Random Forest MAE scores for each fold: [168293.08380021 147030.42912966 138348.51858822 127787.26293543
 181786.07953799]
Gradient Boosting MAE scores for each fold: [161895.11083394 147513.94422814 143822.39706543 126439.63759659
 170139.55475867]
